export const SET_PACKAGE_JSON = 'SET_PACKAGE_JSON';
export const CHANGE_SCRIPT = 'CHANGE_SCRIPT';
export const ADD_OUTPUT_SCRIPT = 'ADD_OUTPUT_SCRIPT';
export const REMOVE_OUTPUT_SCRIPT = 'REMOVE_OUTPUT_SCRIPT';
